### ISSUE TITLE
Application demonstration Video

### ISSUE THREAD

**Issue by YoonDongGyun** [ezwebex/ezwebex#5]
This is demonstration Video about our application. 
[video.zip](https://github.com/ezwebex/ezwebex/files/4849846/video.zip)

**Comment by Alex4386** [comment]
Streamable Media:
[https://gachon.alex4386.me/mobile/demo.mp4](https://gachon.alex4386.me/mobile/demo.mp4)

**Comment by Alex4386** [comment]
issue resolved.
closing issue.
